### PR TITLE
readme: update link

### PR DESCRIPTION
**Pull request by Divkix**
Update the link as the old repository was moved to Github Organinsation.

### CODE REVIEW

**Comment by Divkix** [comment]
Also if possible, I'd like a maintainer to change the link in Special Credits as well.

They can change it to this:
https://telegra.ph/Special-Credits-07-14

**Comment by InukaAsith** [comment]
Ok sir

**Comment by InukaAsith** [comment]
> Also if possible, I'd like a maintainer to change the link in Special Credits as well.
> 
> They can change it to this:
> https://telegra.ph/Special-Credits-07-14

The new daisy bot is fully rewrote by Infotechbro in telethon sir

The pin module of Alita not used in that private source code

Thats why I havent mentioned Alita name in special credits section of @DaisyXbot (in about me section of bot)

**Comment by InukaAsith** [comment]
> Also if possible, I'd like a maintainer to change the link in Special Credits as well.
> 
> They can change it to this:
> https://telegra.ph/Special-Credits-07-14

Anyway I'll add this in next update sir

**Pull request merged**
